//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::click::Entity as Click;
pub use super::connect::Entity as Connect;
pub use super::level::Entity as Level;
pub use super::post::Entity as Post;
pub use super::scene::Entity as Scene;
pub use super::systeminfo::Entity as Systeminfo;
pub use super::user::Entity as User;
